// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: db_template.proto
// Protobuf Java Version: 4.36.0

package org.scaven.database.proto;

@com.google.protobuf.Generated
public interface ColumnOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Column)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * bool isPrimaryKey = 3;
   * </pre>
   *
   * <code>.DataType type = 2;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <pre>
   * bool isPrimaryKey = 3;
   * </pre>
   *
   * <code>.DataType type = 2;</code>
   * @return The type.
   */
  org.scaven.database.proto.DataType getType();
}
