// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: db_template.proto
// Protobuf Java Version: 4.36.0

package org.scaven.database.proto;

@com.google.protobuf.Generated
public final class DbTemplate extends com.google.protobuf.GeneratedFile {
  private DbTemplate() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 36,
      /* patch= */ 0,
      /* suffix= */ "",
      "DbTemplate");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Table_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Table_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Column_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Column_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Row_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Row_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021db_template.proto\"C\n\005Table\022\014\n\004name\030\001 \001" +
      "(\t\022\030\n\007columns\030\002 \003(\0132\007.Column\022\022\n\004rows\030\003 \003" +
      "(\0132\004.Row\"/\n\006Column\022\014\n\004name\030\001 \001(\t\022\027\n\004type" +
      "\030\002 \001(\0162\t.DataType\"\025\n\003Row\022\016\n\006values\030\001 \003(\t" +
      "*E\n\010DataType\022\013\n\007UNKNOWN\020\000\022\007\n\003INT\020\001\022\n\n\006ST" +
      "RING\020\002\022\n\n\006DOUBLE\020\003\022\013\n\007BOOLEAN\020\004B\035\n\031org.s" +
      "caven.database.protoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Table_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_Table_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Table_descriptor,
        new java.lang.String[] { "Name", "Columns", "Rows", });
    internal_static_Column_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_Column_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Column_descriptor,
        new java.lang.String[] { "Name", "Type", });
    internal_static_Row_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_Row_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Row_descriptor,
        new java.lang.String[] { "Values", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
