// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: db_template.proto
// Protobuf Java Version: 4.36.0

package org.scaven.database.proto;

@com.google.protobuf.Generated
public interface RowOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Row)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string values = 1;</code>
   * @return A list containing the values.
   */
  java.util.List<java.lang.String>
      getValuesList();
  /**
   * <code>repeated string values = 1;</code>
   * @return The count of values.
   */
  int getValuesCount();
  /**
   * <code>repeated string values = 1;</code>
   * @param index The index of the element to return.
   * @return The values at the given index.
   */
  java.lang.String getValues(int index);
  /**
   * <code>repeated string values = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the values at the given index.
   */
  com.google.protobuf.ByteString
      getValuesBytes(int index);
}
