// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: db_template.proto
// Protobuf Java Version: 4.36.0

package org.scaven.database.proto;

@com.google.protobuf.Generated
public interface TableOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Table)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>repeated .Column columns = 2;</code>
   */
  java.util.List<org.scaven.database.proto.Column> 
      getColumnsList();
  /**
   * <code>repeated .Column columns = 2;</code>
   */
  org.scaven.database.proto.Column getColumns(int index);
  /**
   * <code>repeated .Column columns = 2;</code>
   */
  int getColumnsCount();
  /**
   * <code>repeated .Column columns = 2;</code>
   */
  java.util.List<? extends org.scaven.database.proto.ColumnOrBuilder> 
      getColumnsOrBuilderList();
  /**
   * <code>repeated .Column columns = 2;</code>
   */
  org.scaven.database.proto.ColumnOrBuilder getColumnsOrBuilder(
      int index);

  /**
   * <code>repeated .Row rows = 3;</code>
   */
  java.util.List<org.scaven.database.proto.Row> 
      getRowsList();
  /**
   * <code>repeated .Row rows = 3;</code>
   */
  org.scaven.database.proto.Row getRows(int index);
  /**
   * <code>repeated .Row rows = 3;</code>
   */
  int getRowsCount();
  /**
   * <code>repeated .Row rows = 3;</code>
   */
  java.util.List<? extends org.scaven.database.proto.RowOrBuilder> 
      getRowsOrBuilderList();
  /**
   * <code>repeated .Row rows = 3;</code>
   */
  org.scaven.database.proto.RowOrBuilder getRowsOrBuilder(
      int index);
}
